# Generated by Django 5.1.7 on 2025-03-27 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrolepermission',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='userrolepermission',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrolepermission',
            name='user',
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='UserRolesPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create_task', models.BooleanField(default=False)),
                ('can_view_task', models.BooleanField(default=False)),
                ('can_update_task', models.BooleanField(default=False)),
                ('can_delete_task', models.BooleanField(default=False)),
                ('can_assign_team', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='UserRolePermission',
        ),
    ]
