# Generated by Django 5.1.7 on 2025-04-09 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_role_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_assign_team',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_create_task',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_delete_task',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_update_task',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_view_task',
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_users', to='permissions.role'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
    ]
